version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8080:80'

  mysql:
      image: mysql:8.0
      ports:
        - "3389:3306"
      environment:
        MYSQL_DATABASE: ${DB_DATABASE:-projeto-coalize}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
        MYSQL_PASSWORD: ${DB_PASSWORD:-userpass}
        MYSQL_USER: ${DB_USERNAME:-username}